from langchain_classic.schema import Document

documents = [
    Document(
        id=1,
        page_content="Renewable energy is derived from natural processes that are replenished constantly. It includes sources like solar and wind.",
        metadata={}
    ),
    Document(
        id=2,
        page_content="Solar power harnesses the energy from the sunlight. Advances in photovoltaic technology have reduced costs significantly.",
        metadata={}
    ),
    Document(
        id=3,
        page_content="Wind energy is generated by converting the kinetic energy of wind into electricity using turbines.",
        metadata={}
    ),
    Document(
        id=4,
        page_content="Hydroelectric power uses the flow of water to generate electricity, and is one of the oldest forms of renewable energy.",
        metadata={}
    ),
    Document(
        id=5,
        page_content="Geothermal energy exploits the heat from the earth, offering a reliable energy source with minimal environmental impact.",
        metadata={}
    ),
    Document(
        id=6,
        page_content="Biomass energy comes from organic materials and is considered renewable when managed sustainably.",
        metadata={}
    ),
    Document(
        id=7,
        page_content="Energy storage technologies are critical to manage the intermittent nature of solar and wind energy.",
        metadata={}
    ),
    Document(
        id=8,
        page_content="The transition to renewable energy helps reduce greenhouse gas emissions and mitigate climate change.",
        metadata={}
    ),
]
