from langchain_classic.schema import Document

# Modified documents with metadata
documents_with_metadata = [
    Document(
        id=1,
        page_content="Renewable energy is derived from natural processes that are replenished constantly. It includes sources like solar and wind.",
        metadata={"year": 2023, "topics": "introduction", "subtopic": "renewable energy"}
    ),
    Document(
        id=2,
        page_content="Solar power harnesses the energy from the sunlight. Advances in photovoltaic technology have reduced costs significantly.",
        metadata={"year": 2023, "topics": "solar power"}
    ),
    Document(
        id=3,
        page_content="Wind energy is generated by converting the kinetic energy of wind into electricity using turbines.",
        metadata={"year": 2023, "topics": "wind energy"}
    ),
    Document(
        id=4,
        page_content="Hydroelectric power uses the flow of water to generate electricity, and is one of the oldest forms of renewable energy.",
        metadata={"year": 2024, "topics": "hydroelectric"}
    ),
    Document(
        id=5,
        page_content="Geothermal energy exploits the heat from the earth, offering a reliable energy source with minimal environmental impact.",
        metadata={"year": 2024, "topics": "geothermal"}
    ),
    Document(
        id=6,
        page_content="Biomass energy comes from organic materials and is considered renewable when managed sustainably.",
        metadata={"year": 2025, "topics": "biomass"}
    ),
    Document(
        id=7,
        page_content="Energy storage technologies are critical to manage the intermittent nature of solar and wind energy.",
        metadata={"year": 2025, "topics": "energy storage"}
    ),
    Document(
        id=8,
        page_content="The transition to renewable energy helps reduce greenhouse gas emissions and mitigate climate change.",
        metadata={"year": 2025, "topics": "environment", "subtopic": "policy"}
    )
]